### ISSUE TITLE
Please add data.corrections.submit

### ISSUE THREAD

**Issue by iaanroux** [AfriGIS-South-Africa/afrigis-services-java#18]
Hi guys,

What would be awesome? If you could add the data.corrections.submit method as described here: https://developers.afrigis.co.za/portfolio/submit-address-api/ to the Java Library too.

**Comment by PieterCachet** [comment]
Issue was been addressed,  Address Submission should be in service soon.

**Comment by demaniak** [comment]
WIP in #19

**Comment by demaniak** [comment]
Closed in #19
