### ISSUE TITLE
Confirm that `details` call also utlizes version 2

### ISSUE THREAD

**Issue by demaniak** [AfriGIS-South-Africa/afrigis-services-java#22]
See https://developers.afrigis.co.za/portfolio/search/#details

**Comment by demaniak** [comment]
@SydneyChadwick did you or @PieterCachet handle the gecode v2 change?

**Comment by SydneyChadwick** [comment]
@demaniak I did the changes. Geocode.details does point to v2, addressed in issue #9

**Comment by PieterCachet** [comment]
I can confirm version 2 call are being used for the Details.
