### ISSUE TITLE
Expand libraries to support ILSE calls

### ISSUE THREAD

**Issue by SydneyChadwick** [AfriGIS-South-Africa/afrigis-services-java#26]

**Comment by demaniak** [comment]
@SydneyChadwick @cfhaasbroek can we maybe get some doc links here?

**Comment by cfhaasbroek** [comment]
We'd specifically like to start with these calls:

1) https://developers.afrigis.co.za/portfolio/census/
2) https://developers.afrigis.co.za/portfolio/afrigis-postal-codes-report/

**Comment by demaniak** [comment]
@SydneyChadwick @cfhaasbroek are we maybe far enough along to break the remaining tasks up into smaller chunks?
