### ISSUE TITLE
Incorrect AG SaaS sign-up url

### ISSUE THREAD

**Issue by demaniak** [AfriGIS-South-Africa/afrigis-services-java#30]
Ref: https://github.com/AfriGIS-South-Africa/afrigis-services-java/blob/master/readme.md

Wrong URL: https://developers.afrigis.co.za/sign-up/

Right URL : https://saasregistration.afrigis.co.za/

**Comment by demaniak** [comment]
@maposatj @petersmythe spotted small error in readme - can you please fix?

Thanks!

**Comment by maposatj** [comment]
Ok changed the URL @demaniak

**Comment by demaniak** [comment]
@maposatj @petersmythe spotted small error in readme - can you please fix?

Thanks!

**Comment by maposatj** [comment]
@demaniak The word TODO?
