### ISSUE TITLE
Implement AG Geocoding version 2

### ISSUE THREAD

**Issue by demaniak** [AfriGIS-South-Africa/afrigis-services-java#7]
Details are still sparse at this point. Please check here for updates.

**Comment by cfhaasbroek** [comment]
**Address Call:**
Request:    point call to intiendols.basic.geocode.address.2
Request:    add addressTypes option list (with add method)
Response:    rename "results" property to "result"
Response:    add "code" property
Response:    add "message" property
Response:    add "source" property

**Comment by cfhaasbroek** [comment]
**Detail Call:**
Request:    point call to intiendols.basic.geocode.details.2
Request:    add addressTypes option list (with add method)
Response:    rename "results" property to "result"
Response:    add "code" property
Response:    add "message" property
Response:    add "source" property

**Comment by cfhaasbroek** [comment]
**List of address types:**
street_address
route
intersection
country
administrative_area_level_1
administrative_area_level_2
administrative_area_level_3
administrative_area_level_4
administrative_area_level_5
colloquial_area
locality
sublocality
postcode_locality
point_of_interest
building
building_level_1
building_level_2
site
site_level_1
site_level_2
site_level_3
site_level_4
site_level_5
site_level_6
